routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/**
 * Admin routes
 */
Route::namespace('Admin')->group(function () {
    Route::get('admin/login', 'LoginController@showLoginForm')->name('admin.login');
    Route::post('admin/login', 'LoginController@login')->name('admin.login');
    Route::get('admin/logout', 'LoginController@logout')->name('admin.logout');
});
Route::group(['prefix' => 'admin', 'middleware' => ['employee'], 'as' => 'admin.' ], function () {
    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => ['role:admin|superadmin|clerk, guard:employee']], function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
            Route::namespace('Products')->group(function () {
                Route::resource('products', 'ProductController');
                Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
                Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
            });
            Route::namespace('Customers')->group(function () {
                Route::resource('customers', 'CustomerController');
                Route::resource('customers.addresses', 'CustomerAddressController');
            });
            Route::namespace('Categories')->group(function () {
                Route::resource('categories', 'CategoryController');
                Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            });
            Route::namespace('Orders')->group(function () {
                Route::resource('orders', 'OrderController');
                Route::resource('order-statuses', 'OrderStatusController');
                Route::get('orders/{id}/invoice', 'OrderController@generateInvoice')->name('orders.invoice.generate');
            });
            Route::resource('addresses', 'Addresses\AddressController');
            Route::resource('cities', 'Cities\CityController');
            Route::resource('pages', 'Pages\PageController')->only(['index', 'edit', 'update']);
            Route::resource('couriers', 'Couriers\CourierController');
            Route::resource('attributes', 'Attributes\AttributeController');
            Route::resource('attributes.values', 'Attributes\AttributeValueController');
            Route::resource('brands', 'Brands\BrandController');
            Route::resource('coupons', 'Coupons\СouponController');
            Route::get('import', 'Products\ImportController@index')->name('import.index');
            Route::post('execute', 'Products\ImportController@execute')->name('import.execute');
        });
        Route::group(['middleware' => ['role:admin|superadmin, guard:employee']], function () {
            Route::resource('employees', 'EmployeeController');
            Route::get('employees/{id}/profile', 'EmployeeController@getProfile')->name('employee.profile');
            Route::put('employees/{id}/profile', 'EmployeeController@updateProfile')->name('employee.profile.update');
            Route::resource('roles', 'Roles\RoleController');
            Route::resource('permissions', 'Permissions\PermissionController');
        });
    });
});

/**
 * Frontend routes
 */
Auth::routes();
Route::namespace('Auth')->group(function () {
    Route::get('cart/login', 'CartLoginController@showLoginForm')->name('cart.login');
    Route::post('cart/login', 'CartLoginController@login')->name('cart.login');
    Route::get('logout', 'LoginController@logout');
});

Route::namespace('Front')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['middleware' => ['auth', 'web']], function () {

        Route::namespace('Payments')->group(function () {
            Route::get('bank-transfer', 'BankTransferController@index')->name('bank-transfer.index');
            Route::post('bank-transfer', 'BankTransferController@store')->name('bank-transfer.store');
        });

        Route::namespace('Addresses')->group(function () {
            Route::resource('country.state', 'CountryStateController');
            Route::resource('state.city', 'StateCityController');
        });

        Route::get('accounts', 'AccountsController@index')->name('accounts');
        Route::get('checkout', 'CheckoutController@index')->name('checkout.index');
        Route::post('checkout', 'CheckoutController@store')->name('checkout.store');
        Route::get('checkout/execute', 'CheckoutController@executePayPalPayment')->name('checkout.execute');
        Route::post('checkout/execute', 'CheckoutController@charge')->name('checkout.execute');
        Route::get('checkout/cancel', 'CheckoutController@cancel')->name('checkout.cancel');
        Route::get('checkout/success', 'CheckoutController@success')->name('checkout.success');
        Route::resource('customer.address', 'CustomerAddressController');
        Route::post('change-password', 'AccountsController@changePassword')->name('change.password');
        Route::post('update-personal-data/{customer}', 'AccountsController@update')->name('update.personal.data');
        Route::get('clear-favorites', 'AccountsController@clearFavorites')->name('clear.favorites');
    });

    //pages
    Route::get('delivery-and-pay', 'HomeController@delivery')->name('delivery');
    Route::get('change-city/{city}', 'HomeController@changeCity')->name('change-city');
    Route::get('pages/{slug}', 'HomeController@show')->name('pages.show');

    Route::get('cart/deferred', 'CartController@deferred')->name('cart.deferred');
    Route::resource('cart', 'CartController');
    Route::get('cart-clear', 'CartController@clear')->name('cart.clear');
    Route::post('usePostCard/{rowId}', 'CartController@usePostCard')->name('usePostCard');
    Route::post('courierChange/{courierId}', 'CartController@courierChange')->name('courierChange');
    Route::post('totalPrice', 'CartController@getTotalPrice')->name('totalPrice');
    Route::get("category/{slug}", 'CategoryController@getCategory')->name('front.category.slug');
    Route::get("brand/{slug}", 'CategoryController@getBrand')->name('front.brand.slug');
    Route::get("search", 'ProductController@search')->name('search.product');
    Route::get("{product}", 'ProductController@show')->name('front.get.product');
    Route::post('addToFavorite/{product}', 'HomeController@addToFavorite')->name('addToFavorite');
    Route::post('setCoupon/{coupon}', 'CartController@setCoupon')->name('setCoupon');
    Route::post('setWishes', 'CartController@setWishes')->name('setWishes');
    Route::post('destroyCoupon', 'CartController@destroyCoupon')->name('destroyCoupon');
});

app/Http/Controllers/Admin/Products/ImportController.php
<?php

namespace App\Http\Controllers\Admin\Products;

use App\Shop\Attributes\Attribute;
use App\Shop\AttributeValues\AttributeValue;
use App\Shop\Categories\Category;
use App\Shop\ProductImages\ProductImage;
use App\Shop\Products\Product;
use App\Shop\Products\Repositories\Interfaces\ProductRepositoryInterface;
use Google_Client;
use Google_Service_Drive;
use Google_Service_Sheets;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class ImportController extends Controller
{
    private $client;

    private $productRepo;

    public function __construct(ProductRepositoryInterface $productRepository)
    {
        $this->productRepo = $productRepository;
    }

    public function index()
    {
        return view('admin.import.index');
    }

    public function setClientSettings()
    {
        $this->client = new Google_Client();
        $this->client->setApplicationName('Google Sheets and PHP');
        $this->client->setScopes([Google_Service_Sheets::SPREADSHEETS, Google_Service_Drive::DRIVE]);
        $this->client->setAccessType('offline');
        $this->client->setAuthConfig(public_path('google.json'));
    }

    public function getIdFromUrl($url) {
        preg_match('/[-\w]{25,}/', $url, $matches);
        return $matches[0];
    }

    public function execute(Request $request)
    {
        if (isset($request->address)) {
            $this->setClientSettings();
            $service = new Google_Service_Sheets($this->client);
            $driveService = new Google_Service_Drive($this->client);

            $response = $service->spreadsheets_values->get($request->address, "Лист1!A2:N100");
            $rows = $response->getValues();

            if (empty($rows)) {
                return redirect()->route('admin.import.index')->with('error', 'Таблица пуста');
            }

            foreach ($rows as $row) {

                $product = Product::updateOrCreate(
                    ['sku' => $row[1]],
                    [
                        'slug'        => str_slug($row[2]),
                        'sku'         => $row[1],
                        'name'        => $row[2],
                        'description' => $row[3],
                        'status'      => 1,
                        'quantity'    => (int)$row[5],
                        'is_sale'     => ($row[6] == 1) ? 1 : 0,
                        'price'       => (int)$row[7],
                        'sale_price'  => (int)$row[8],
                    ]
                );

                if (!empty($row[4])) {
                    $product->images()->delete();
                    $folderId = $this->getIdFromUrl($row[4]);
                    $optParams = [
                        'q' => "'" . $folderId . "' in parents",
                        'fields' => 'files(id, name)'
                    ];
                    $result = $driveService->files->listFiles($optParams);
                    $files = $result->getFiles();

                    if (count($files) > 0) {
                        foreach ($files as $k => $file) {
                            $content = $driveService->files->get($file->getId(), ['alt' => 'media']);
                            Storage::disk('public')->put('products/' . $file->getName(), $content->getBody()->getContents());
                            switch ($k) {
                                case 0:
                                    $product->cover = 'products/' . $file->getName();
                                    $product->save();
                                    break;
                                case 1:
                                    $product->cover_hover = 'products/' . $file->getName();
                                    $product->save();
                                    break;
                                default:
                                    $productImage = new ProductImage([
                                        'product_id' => $product->id,
                                        'src' => 'products/' . $file->getName()
                                    ]);
                                    $product->images()->save($productImage);
                            }
                        }
                    }
                }

                // привязка продукта в категории
                if (!empty($row[0])) {
                    $categories = explode(';', $row[0]);
                    $params = [];
                    foreach ($categories as $k => $category) {
                        $cat = Category::where('name', $category)->first();
                        if (isset($cat)) {
                            $params[$k] = $cat->id;
                        }
                    }
                    $product->categories()->sync($params);
                } else {
                    $product->detachCategories();
                }


                // обновление размеров и хэштегов
                $product->attributesValues()->detach();
                $attributes = [];
                if (!empty($row[9]))
                {
                    $sizes = explode(';', $row[9]);
                    foreach ($sizes as $size) {
                        if(!empty($size)) {
                            $attribute = AttributeValue::where('name', $size)->first();
                            if (isset($attribute)) {
                                $attributes[] = $attribute->id;
                            }
                        }
                    }
                }

                $hashtagAttribute = Attribute::where('name', 'Hashtags')->first();

                if (!empty($row[10]) && isset($hashtagAttribute))
                {
                    $hashtags = explode(';', $row[10]);
                    foreach ($hashtags as $tag) {
                        if (!empty($tag)) {
                            $attribute = AttributeValue::firstOrCreate(
                                ['name' => $tag],
                                [
                                    'name'         => $tag,
                                    'value'        => str_slug($tag),
                                    'attribute_id' => $hashtagAttribute->id
                                ]
                            );
                            $attributes[] = $attribute->id;
                        }
                    }
                }

                $product->attributesValues()->sync($attributes);

            }
            return redirect()->route('admin.import.index')->with('message', 'Имортирование прошло успешно');
        }
    }
}

app/Http/Controllers/Front/AccountsController.php
<?php

namespace App\Http\Controllers\Front;

use App\Rules\MatchOldPassword;
use App\Shop\Couriers\Repositories\Interfaces\CourierRepositoryInterface;
use App\Shop\Customers\Customer;
use App\Shop\Customers\Repositories\CustomerRepository;
use App\Shop\Customers\Repositories\Interfaces\CustomerRepositoryInterface;
use App\Http\Controllers\Controller;
use App\Shop\Favorites\Favorites;
use App\Shop\Orders\Order;
use App\Shop\Orders\Transformers\OrderTransformable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class AccountsController extends Controller
{
    use OrderTransformable;

    /**
     * @var CustomerRepositoryInterface
     */
    private $customerRepo;

    /**
     * @var CourierRepositoryInterface
     */
    private $courierRepo;

    /**
     * AccountsController constructor.
     *
     * @param CourierRepositoryInterface $courierRepository
     * @param CustomerRepositoryInterface $customerRepository
     */
    public function __construct(
        CourierRepositoryInterface $courierRepository,
        CustomerRepositoryInterface $customerRepository
    ) {
        $this->customerRepo = $customerRepository;
        $this->courierRepo = $courierRepository;
    }

    public function index()
    {
        $customer = $this->customerRepo->findCustomerById(auth()->user()->id);

        $customerRepo = new CustomerRepository($customer);
        $orders = $customerRepo->findOrders(['*'], 'created_at');

        $orders->transform(function (Order $order) {
            return $this->transformOrder($order);
        });

        $orders->load('products', 'products.attributesValues');
        $favorites = $customer->favorites()->with('attributesValues')->get();

        return view('front.accounts', [
            'customer' => $customer,
            'orders' => $this->customerRepo->paginateArrayResults($orders->toArray(), 15),
            'favorites' => $favorites
        ]);
    }

    public function changePassword(Request $request)
    {
        $messages = [
            'required' => 'Поля для смены пароля обязательны к заполнению',
            'same:new_password' => 'Вы не правильно повторили новый пароль',
        ];
        $validator = Validator::make($request->all(), [
            'password' => ['required', new MatchOldPassword],
            'new_password' => ['required'],
            'new_confirm_password' => ['required', 'same:new_password'],
        ], $messages);

        if ($validator->fails()) {
            return redirect()->route('accounts', ['tab' => 'personal'])->withErrors($validator);
        }

        Customer::find(auth()->user()->id)->update(['password'=> Hash::make($request->new_password)]);

        return redirect()->route('accounts', ['tab' => 'personal'])
            ->with('message', 'Пароль успешно изменен');
    }

    public function update(Request $request, Customer $customer)
    {
        $customer->update($request->all());
        return redirect()->route('accounts', ['tab' => 'personal'])
            ->with('message', 'Контактные данные успешно изменены');
    }

    public function clearFavorites()
    {
        $customer = $this->customerRepo->findCustomerById(auth()->user()->id);
        $customer->favorites()->detach();
        return redirect()->route('accounts', ['tab' => 'favorites'])
            ->with('message', 'Все товары удалены из избранного');
    }

}

app/Http/Controllers/Front/Payments/Equier.php
<?php

namespace App\Http\Controllers\Front\Payments;

use GuzzleHttp\Client;

abstract class Equier
{
    protected function setClient()
    {
        $this->client = new Client([
            'base_uri' => $this->baseUri,
        ]);
    }
}

resources/views/front/products/featured.blade.php
<!-- START SECTION 1 -->
<section class="s s-primary" id="s1">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 text-center">
                <h2>Авторские букеты в Москве</h2>
            </div>
        </div>

        <div class="row featured">

            @foreach($brandsWithLastProduct as $brand)
                <?php $product = $brand->lastProduct ?>
            @if(isset($product))
                <div class="col-xs-12 col-sm-4 featured-item">
                    <h3 class="ico-h {{ $brand->cover_icon }} text-center">{{ $brand->name }}</h3>
                    <div class="featured-item__body">
                        <!-- START: IMAGE -->
                        <div class="featured-item__images">
                            @if($product->is_sale == 1)
                                <span class="badge" title="Акция"> {{ 100 - round($product->sale_price*100/$product->price) }}
                                    %</span>
                            @endif
                            <span data-toggle="featured" data-id="{{ $product->id }}" class="{{ $product->isFeatured() }}"></span>
                            <a href="{{ route('front.get.product', str_slug($product->slug)) }}">
                                <img src="{{ asset("storage/".$product->cover) }}" alt="{{ $product->name }}"
                                     class="img-responsive featured-item__top-image">
                                <img src="{{ asset("storage/".$product->cover_hover) }}" alt="{{ $product->name }}"
                                     class="img-responsive featured-item__bot-image">
                            </a>
                            <span class="featured-item__tags">
								@foreach($product->attributesValues as $attr)
                                    @if($attr->attribute->name == 'Hashtags')
                                        <a href="javascript:void(0);" data-type="tag">{{ $attr->name }}</a>
                                    @endif
                                @endforeach
							</span>

                        </div>
                        <!-- END: IMAGE -->

                        <div class="featured-item__info">
                            <div class="col-xs-5">
                                <span class="featured-item__title">Букет №{{ $product->id }}</span>
                            </div>
                            <div class="col-xs-7 text-right">

                                @if($product->is_sale == 1)
                                    <span class="featured-item__price">
                                        <span class="featured-item__price-old">
                                        {{ round($product->price) }} р.
                                        </span>
                                        {{ round($product->sale_price) }} р.
                                    </span>
                                @else
                                    <span class="featured-item__price">{{ round($product->price) }} р.</span>
                                @endif

                            </div>
                        </div>

                    </div>
                    <div class="featured-item__footer">
                        <a href="{{ route('front.brand.slug', str_slug($brand->name)) }}">
                        @switch($brand->name)
                        @case('К празднику')
                            Ещё букеты к празднику
                        @break

                        @case('Акция')
                            Ещё букеты по акции
                        @break

                        @case('Популярное')
                            Все популярные букеты
                        @break

                        @default
                            Смотреть все букеты
                        @endswitch
                        </a>
                    </div>
                </div>
            @endif
            @endforeach

        </div>
    </div>
</section>

resources/views/front/products/product-list-table.blade.php
@if(!$products->isEmpty())
<div class="row">
    <div class="col-md-12">
        <!-- <div class="row header hidden-xs hidden-sm"> -->
        <div class="row hidden-xs hidden-sm" style="height: 40px;">
            <div class="col-lg-2 col-md-2 col-sm-4 col-xs-4">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><b>Cover</b></div>
                </div>
            </div>

            <div class="col-lg-10 col-md-10 col-sm-8 col-xs-8">
                <div class="row">
                    <div class="col-lg-5 col-md-5"><b>Name</b></div>
                    <div class="col-lg-2 col-md-2"><b>Quantity</b></div>
                    <div class="col-lg-1 col-md-1"><b>Remove</b></div>
                    <div class="col-lg-2 col-md-2"><b>Price</b></div>
                    <div class="col-lg-2 col-md-2"><b>Total</b></div>
                </div>
            </div>
        </div>
        @foreach($cartItems as $cartItem)
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-3 col-xs-4">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 text-center">
                            <a href="{{ route('front.get.product', [$cartItem->product->slug]) }}" class="hover-border">
                                @if(isset($cartItem->cover))
                                    <img src="{{$cartItem->cover}}" alt="{{ $cartItem->name }}" class="img-responsive img-thumbnail">
                                @else
                                    <img src="https://placehold.it/120x120" alt="" class="img-responsive img-thumbnail">
                                @endif
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10 col-sm-9 col-xs-8">
                    <div class="row">
                        <div class="col-lg-5 col-md-5 col-sm-12 col-xs-12">
                            <h4 style="margin-bottom:5px;">{{ $cartItem->name }}</h4>
                            @if($cartItem->options->has('combination'))
                                <div style="margin-bottom:5px;">
                                @foreach($cartItem->options->combination as $option)
                                    <small class="label label-primary">{{$option['value']}}</small>
                                @endforeach
                                </div>
                            @endif
                            <!-- <div class="product-description"> -->
                                {!! $cartItem->product->description !!}
                            <!-- </div> -->
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-4 col-xs-8">
                            <form action="{{ route('cart.update', $cartItem->rowId) }}" class="form-inline" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="put">
                                <div class="input-group">
                                    <input type="text" name="quantity" value="{{ $cartItem->qty }}" class="form-control input-sm" />
                                    <span class="input-group-btn"><button class="btn btn-default btn-sm">Update</button></span>
                                </div>
                            </form>
                        </div>
                        <div class="col-lg-1 col-md-1 col-sm-8 col-xs-4">
                            <form action="{{ route('cart.destroy', $cartItem->rowId) }}" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="delete">
                                <button onclick="return confirm('Are you sure?')" class="btn btn-danger btn-sm"><i class="fa fa-times"></i></button>
                            </form>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            <span class="hidden-lg hidden-md"><small>Tax: </span>
                            {{config('cart.currency')}} {{ number_format(($cartItem->qty*$cartItem->tax), 2) }}</small>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            <span class="hidden-lg hidden-md"><small>Subtotal: </span>
                            {{config('cart.currency')}} {{ number_format($cartItem->price, 2) }}</small>
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            <span class="hidden-lg hidden-md"><small>Total: </span>
                            {{config('cart.currency')}} {{ number_format(($cartItem->qty*$cartItem->price), 2) }}</small>
                        </div>
                    </div>
                </div>
            </div>
            <br>
        @endforeach
    </div>
</div>
@endif
<script type="text/javascript">
    $(document).ready(function () {
        let courierRadioBtn = $('input[name="rate"]');
        courierRadioBtn.click(function () {
            $('#shippingFee').text($(this).data('fee'));
            let totalElement = $('span#grandTotal');
            let shippingFee = $(this).data('fee');
            let total = totalElement.data('total');
            let grandTotal = parseFloat(shippingFee) + parseFloat(total);
            totalElement.html(grandTotal.toFixed(2));
        });
    });
</script>

resources/views/front/products/product-list.blade.php
@if(!empty($products) && !collect($products)->isEmpty())
    <ul class="row text-center list-unstyled">
        @foreach($products as $product)
            <li class="col-md-3 col-sm-6 col-xs-12 product-list">
                <div class="single-product">
                    <div class="product">
                        <div class="product-overlay">
                            <div class="vcenter">
                                <div class="centrize">
                                    <ul class="list-unstyled list-group">
                                        <li>
                                            <form action="{{ route('cart.store') }}" class="form-inline" method="post">
                                                {{ csrf_field() }}
                                                <input type="hidden" name="quantity" value="1" />
                                                <input type="hidden" name="product" value="{{ $product->id }}">
                                                <button id="add-to-cart-btn" type="submit" class="btn btn-warning" data-toggle="modal" data-target="#cart-modal"> <i class="fa fa-cart-plus"></i> Add to cart</button>
                                            </form>
                                        </li>
                                        <li>  <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myModal_{{ $product->id }}"> <i class="fa fa-eye"></i> Quick View</button>
                                        <li>  <a class="btn btn-default product-btn" href="{{ route('front.get.product', str_slug($product->slug)) }}"> <i class="fa fa-link"></i> Go to product</a> </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        @if(isset($product->cover))
                            <img src="{{ asset("storage/$product->cover") }}" alt="{{ $product->name }}" class="img-bordered img-responsive">
                        @else
                            <img src="https://placehold.it/263x330" alt="{{ $product->name }}" class="img-bordered img-responsive" />
                        @endif
                    </div>

                    <div class="product-text">
                        <h4>{{ $product->name }}</h4>
                        <p>
                            {{ config('cart.currency') }}
                            @if(!is_null($product->attributes->where('default', 1)->first()))
                                @if(!is_null($product->attributes->where('default', 1)->first()->sale_price))
                                    {{ number_format($product->attributes->where('default', 1)->first()->sale_price, 2) }}
                                    <p class="text text-danger">Sale!</p>
                                @else
                                    {{ number_format($product->attributes->where('default', 1)->first()->price, 2) }}
                                @endif
                            @else
                                {{ number_format($product->price, 2) }}
                            @endif
                        </p>
                    </div>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal_{{ $product->id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                @include('layouts.front.product')
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        @endforeach
        @if($products instanceof \Illuminate\Contracts\Pagination\LengthAwarePaginator)
            <div class="row">
                <div class="col-md-12">
                    <div class="pull-left">{{ $products->links() }}</div>
                </div>
            </div>
        @endif
    </ul>
@else
    <p class="alert alert-warning">No products yet.</p>
@endif